 @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjM0NmZkMjE4ZDJmMDEyNGNiMjRmZSIsImVtYWlsIjoibGVwaHVkYXQuOThAZ21haWwuY29tIiwidXNlcm5hbWUiOiJsZXBodWRhdDk4IiwiaWF0IjoxNzQ3MjAxMDI4LCJleHAiOjE3NDk3OTMwMjh9.gVMcLkLGLjSTKhsWYlpiYROCJbvEuzwEyc0Uno6pzXo
@email = writephudat@gmail.com
@password = 123

# Signup
POST http://localhost:3056/api/v1/auth/signup
Content-Type: application/json


 {
  "email": "{{email}}",
  "password": "{{password}}"
}



###

# Verify Email (replace with a valid token)
GET http://localhost:3056/api/v1/auth/verify-email/YOUR_VERIFICATION_TOKEN

###

# Login
# POST https://www.djav.space/api/v1/auth/login
POST http://localhost:3056/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}



###

# Validate OTP
POST http://localhost:3056/api/v1/auth/validate-otp
Content-Type: application/json

{
  "email": "test@example.com",
  "otp": "123456"
}

###

# Forgot Password
POST http://localhost:3056/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "test@example.com"
}

###

# Reset Password
POST http://localhost:3056/api/v1/auth/reset-password
Content-Type: application/json

{
  "token": "YOUR_RESET_TOKEN",
  "newPassword": "newSecurePassword"
}

###

# Resend Verification
POST http://localhost:3056/api/v1/auth/resend-verification
Content-Type: application/json

{
  "email": "lephudat.98@gmail.com"
}

###

# Check Me (requires a valid JWT token in the Authorization header)
GET http://localhost:3056/api/v1/auth/check-me
Authorization: Bearer YOUR_JWT_TOKEN